/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录凭证(name+password) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_auth.loginBody"];
                };
            };
            responses: {
                /** @description code/message/data{token,user} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description 凭证错误 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description logged_out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录用户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出变更 */
        get: {
            parameters: {
                query?: {
                    /** @description 状态过滤(pending|approved|rejected) */
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 变更列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批准变更 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 审批人(默认 user) */
                    "X-User"?: string;
                };
                path: {
                    /** @description 变更ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description 非 pending 状态 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/changes/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝变更 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 审批人(默认 user) */
                    "X-User"?: string;
                };
                path: {
                    /** @description 变更ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description rejected */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description 非 pending 状态 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目空间 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 项目空间列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建项目空间 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 项目空间(name+slug) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_workspace.CreateProjectSpaceInput"];
                };
            };
            responses: {
                /** @description 创建的项目空间 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取项目空间详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 项目空间 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description project space not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/apps/{aid}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出应用需求池 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                    /** @description 应用ID */
                    aid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 需求列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/my-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的任务聚合 */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 用户名(默认 anonymous) */
                    "X-User"?: string;
                };
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description roles/toClaim/myDev/toApprove/toRelease */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目空间概览 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 概览统计 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目空间下的项目 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 项目列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建项目 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 项目(name+slug) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_workspace.CreateProjectInput"];
                };
            };
            responses: {
                /** @description 创建的项目 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 发布历史 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 发布列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 发布上线 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 发布入参(change_id) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_release.createRequest"];
                };
            };
            responses: {
                /** @description version/status/deploy_triggered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description 测试门禁拦截 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目空间需求 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 需求列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建需求(AI生成规格) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 需求(application_id?/description/images?) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_requirement.createRequest"];
                };
            };
            responses: {
                /** @description 创建的需求 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/requirements/{rid}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 认领需求 */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description 用户名(默认 anonymous) */
                    "X-User"?: string;
                };
                path: {
                    /** @description 项目空间ID */
                    id: string;
                    /** @description 需求ID */
                    rid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description assigned_to */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description 已被他人认领 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/requirements/{rid}/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI拆解需求为子任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                    /** @description 需求ID */
                    rid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/requirements/{rid}/dispatch-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 派发编码任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                    /** @description 需求ID */
                    rid: string;
                };
                cookie?: never;
            };
            /** @description 编码参数(repo_dir?/model?) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_requirement.dispatchRequest"];
                };
            };
            responses: {
                /** @description task_id/status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/requirements/{rid}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 释放需求认领 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                    /** @description 需求ID */
                    rid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description released */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出项目级规范 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 项目级规范列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新建项目级规范 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["internal_standard.createBody"];
            responses: {
                /** @description 创建的规范 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project-spaces/{id}/standards/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预览生效规范 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 项目空间ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description standards/prompt_section */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出规则 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 规则列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新建规则 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 规则(name/condition 等) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_rule.createRequest"];
                };
            };
            responses: {
                /** @description 创建的规则 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 规则校验 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 校验入参(scope/field/content) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_rule.checkRequest"];
                };
            };
            responses: {
                /** @description violations/blocked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新规则 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规则ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 规则新值 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_rule.updateRequest"];
                };
            };
            responses: {
                /** @description 更新后的规则 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        /** 删除规则 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规则ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description id/deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rules/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 启用/禁用规则 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规则ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description enabled */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_rule.setEnabledRequest"];
                };
            };
            responses: {
                /** @description id/enabled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全局规范 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 全局规范列表 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新建全局规范 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["internal_standard.createBody"];
            responses: {
                /** @description 创建的规范 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新规范 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规范ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 规范新值 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_standard.updateBody"];
                };
            };
            responses: {
                /** @description 更新后的规范 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        post?: never;
        /** 删除规范 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规范ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description id/deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 启用/禁用规范 */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 规范ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description enabled */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_standard.setEnabledBody"];
                };
            };
            responses: {
                /** @description id/enabled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description invalid body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "internal_auth.loginBody": {
            name: string;
            password: string;
        };
        "internal_release.createRequest": {
            change_id: string;
        };
        "internal_requirement.createRequest": {
            /** @description 可选：归属应用 */
            application_id?: string;
            description: string;
            /** @description data URL 或 http URL */
            images?: string[];
        };
        "internal_requirement.dispatchRequest": {
            model?: string;
            /** @description 可选；空=用需求归属应用的托管仓库 */
            repo_dir?: string;
        };
        "internal_rule.checkRequest": {
            content?: string;
            field?: string;
            scope?: string;
        };
        "internal_rule.createRequest": {
            action?: string;
            category?: string;
            condition: string;
            condition_field?: string;
            description?: string;
            enabled?: boolean;
            name: string;
            scope?: string;
            type?: string;
        };
        "internal_rule.setEnabledRequest": {
            enabled?: boolean;
        };
        "internal_rule.updateRequest": {
            action?: string;
            category?: string;
            condition: string;
            condition_field?: string;
            description?: string;
            enabled?: boolean;
            name: string;
            scope?: string;
            type?: string;
        };
        "internal_standard.createBody": {
            category?: string;
            content: string;
            enabled?: boolean;
            name: string;
            priority?: number;
        };
        "internal_standard.setEnabledBody": {
            enabled?: boolean;
        };
        "internal_standard.updateBody": {
            category?: string;
            content: string;
            enabled?: boolean;
            name: string;
            priority?: number;
        };
        "internal_workspace.CreateProjectInput": {
            name: string;
            slug: string;
        };
        "internal_workspace.CreateProjectSpaceInput": {
            name: string;
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description 规范(name/content 等) */
        "internal_standard.createBody": {
            content: {
                "application/json": components["schemas"]["internal_standard.createBody"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
